ローカライズされたコンテンツに投稿いただき、ありがとうございます。 
コンテンツに対するすべての投稿は、次のガイドラインに従う必要があります。
1. [Microsoft 言語スタイル ガイド](https://www.microsoft.com/Language/StyleGuides)。英語から別の言語に翻訳するときにテキストをどのように表記するかを説明します。
2. [Microsoft ランゲージ ポータル](https://www.microsoft.com/language)。Microsoft 製品で使用される技術**用語** (英語) と、対応する翻訳を提供します。
拡大しているローカライズ コミュニティに参加する際には、[コミュニティのローカライズ Wiki](https://github.com/Microsoft/Localization/wiki) にアクセスして、コミュニティのローカライズ プログラムと、プログラムへの他の投稿方法に関する詳細をご確認ください。このページでは、PR 承認プロセスに加え、いくつかの <PR 管理> のヒントを紹介しています。
<ローカライズ> の投稿に対する報酬としてポイントを獲得できるため、投稿を続け、[投稿者のランキング](https://microsoftl10n.github.io/) でさらに高いレベルを達成しましょう!

Microsoft 開発者リレーションシップの国際的なグループ
